FROM node:latest as node
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --prod

FROM node:alpine
WORKDIR /app
COPY --from=node /app/dist/dbms/browser /app
RUN npm install -g http-server

EXPOSE 8080

CMD ["http-server", "-p", "8080", "-g", "true"]